### ISSUE TITLE
Add Anchor Mixin 

### ISSUE THREAD

**Issue by ronalfy** [bigwing/nest-starter-theme#6]
```scss
@mixin anchors( $default, $link, $visited, $active, $focus, $hover ) {
	a {
		&         { color: $default; }
		&:link    { color:$link; }
		&:visited { color:$visited; }
		&:active  { color:$active; }
		&:focus   { color:$focus; }
		&:hover   { color:$hover; }

	}
}

```
